### ISSUE TITLE
data access and security breakout

### ISSUE THREAD

**Issue by raynamharris** [dcppc/2018-july-workshop#13]
Proposed by @karenmdavis of KC6 / Team Helium

**Comment by raynamharris** [comment]
Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/578893575

Or iPhone one-tap :
    US: +14086380968,,578893575#  or +16468769923,,578893575# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 408 638 0968  or +1 646 876 9923  or +1 669 900 6833 
    Meeting ID: 578 893 575
    International numbers available: https://zoom.us/u/rjbRNmY

**Comment by karenmdavis** [comment]
This is the same as breakout #8 -- I didn't realize that I had requested it, and that Cathy/Alastair also requested it.

**Comment by raynamharris** [comment]
Thanks @karenmdavis. I'll close this in favor of the other breakout.
